--- # Upload the Shell Script to Remote Host and Run it.
-  hosts: Sonar-Server
   remote_user: ec2-user
   become: yes
   become_method: sudo
   connection: ssh
   gather_facts: yes    
   vars:
      java_packages:
        - java-1.8.0-openjdk
   roles:
     - geerlingguy.java
     - ansible-role-sonarqube
